services:
  altcha-lite:
    container_name: altcha-lite
    image: xhunt3rx/altcha-lite
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - ALTCHA_HMAC_KEY=MY_ALTCHA_HMAC_KEY
      - EXPIRE_TIME_IN_MINS=5
      - CACHE_CLEAN_INTERVAL_MINS=15
